bbs/bbs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views
from django.views.static import serve
from django.conf import settings
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.Login.as_view()),
    url(r'^login2/$', views.login2),
    url(r'^pcgetcaptcha/$', views.pcgetcaptcha),

    url(r'^index/$', views.Index.as_view()),
    url(r'^v-code/$', views.v_code),
    # ------ day75 ↓ -----------
    url(r'^reg/$', views.RegView.as_view()),
    url(r'^logout/$', views.logout),
    # 给用户上传文件 配置一个处理的路由
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

    # ------- day77 ↓ ------------
    # 二级路由
    url(r'^blog/', include(blog_urls)),

    # 点赞
    url(r'^mengmeng/$', views.mengmeng),
    # day80
    url(r'^comment/(\d+)$', views.Comment.as_view()),
    # day79
    url(r'^comment/$', views.comment),

    url(r'^$', views.Index.as_view()),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

bbs/blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    phone = models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号')  # 手机号
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png")  # 头像

    blog = models.OneToOneField(to="Blog", null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    title = models.CharField(max_length=64)  # 个人博客标题
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "博客"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog")  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return "{}-{}".format(self.blog.title, self.title)

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog")  # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=50, verbose_name='文章标题')  # 文章标题
    desc = models.CharField(max_length=255)  # 文章描述
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    category = models.ForeignKey(to="Category", null=True, blank=True)  # 文章分类
    user = models.ForeignKey(to="UserInfo")  # 作者
    tags = models.ManyToManyField(  # 文章的标签
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),
    )

    # 评论数
    comment_count = models.IntegerField(default=0)
    # 点赞数
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    def __str__(self):
        return "{}-{}".format(self.user.username, self.title)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    content = models.TextField()  # 文章内容
    article = models.OneToOneField(to="Article")

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    article = models.ForeignKey(to="Article")
    tag = models.ForeignKey(to="Tag")

    def __str__(self):
        return "{}-{}".format(self.article, self.tag)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)  # 点赞还是踩灭

    def __str__(self):
        return "{}-{}".format(self.user_id, self.article_id)

    class Meta:
        unique_together = (("article", "user"),)  # 同一个人只能给一篇文章点一次赞
        verbose_name = "点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    article = models.ForeignKey(to="Article")
    user = models.ForeignKey(to="UserInfo")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)

    parent_comment = models.ForeignKey("self", null=True, blank=True)  # 自己关联自己

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

bbs/blog/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        min_length=4,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名不能少于4位"
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}
        )
    )
    password = forms.CharField(
        label="密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )


# 注册Form类
class RegisterForm(forms.Form):
    username = forms.CharField(
        label='用户名',
        min_length=4,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名不能少于4位"
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}
        )
    )
    password = forms.CharField(
        label="密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )
    re_password = forms.CharField(
        label="确认密码",
        min_length=6,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码不能少于6位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )
    phone = forms.CharField(
        label='手机号',
        error_messages={
            "required": "手机号不能为空",
        },
        validators=[RegexValidator(r'1[3-9]\d{9}', "手机号码格式不正确")],
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}
        )
    )
    email = forms.CharField(
        label='邮箱',
        error_messages={
            "required": "邮箱不能为空",
        },
        validators=[RegexValidator(r'^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}$', "邮箱格式不正确")],
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"}
        )
    )

    # 全局钩子
    def clean(self):
        pwd = self.cleaned_data.get("password")
        re_pwd = self.cleaned_data.get("re_password")
        if re_pwd and re_pwd == pwd:
            return self.cleaned_data
        else:
            self.add_error('re_password', "两次密码不一致")
            raise ValidationError("两次密码不一致")

bbs/templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加新页面</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="标题">
                </div>
                <div class="form-group">
                    <label for="content">内容</label>
                    <textarea class="form-control" name="content" id="content" cols="30" rows="20"></textarea>
                </div>

                <div class="form-group">
                    <label for="category">文章分类</label>
                    <select name="category" id="category" class="form-control">
                        {% for category in category_list %}
                            <option value="{{ category.id }}">{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-success">发布</button>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/jquery.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-all.js"></script>
<script charset="utf-8" src="/static/plugins/kindeditor/lang/zh-CN.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#content', {
                    "uploadJson": "/blog/upload/",
                    "extraFileUploadParams": {"csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()}
                });
        });
</script>
</body>
</html>

bbs/templates/article.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="article-content">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>
    {% csrf_token %}
    <hr>
    <!-- 点赞 开始-->
    <div class="clearfix">
        <div id="div_digg">
            <!-- 点赞 -->
            <div class="diggit digg">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <!-- 反对 -->
            <div class="buryit digg">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear"></div>
            <!-- 提示信息 -->
            <div class="diggword" id="digg_tips"></div>
        </div>
    </div>
    <!-- 点赞 结束-->

    <!-- 评论展示区 开始-->
    <h4>评论：</h4>
    <div>
        <div class="list-group comment-list">
            {% for comment in comment_list %}
                <div href="#" class="list-group-item" my-id="{{ comment.id }}">
                    <h4 class="list-group-item-heading comment-header">
                        <span>{{ forloop.counter }}楼</span>
                        <span>{{ comment.create_time|date:'Y-m-d H:i' }}</span>
                        <span>{{ comment.user.username }}</span>
                        <span class="pull-right replay">回复</span>
                    </h4>
                    {% if comment.parent_comment %}
                        <span style="display: block">@{{ comment.parent_comment.user.username }}</span>
                        <p class="list-group-item-text well">
                            {{ comment.parent_comment.content }}
                        </p>
                    {% endif %}
                    <p class="list-group-item-text comment-content">
                        {{ comment.content }}
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- 评论展示区 结束-->
    <hr>

    <!-- 发表评论 开始 -->
    <h4>发表评论</h4>
    <div>
        <span>用户名：</span>
        <input type="text" value="{{ request.user.username }}" disabled>
    </div>
    <div>
        <p>发表评论：</p>
        <textarea id="new-comment" cols="60" rows="10">

        </textarea>
    </div>
    <div>
        <button id="submit-comment" class="btn btn-success">提交</button>
    </div>
    <!-- 发表评论 结束 -->


    <div style="height: 300px"></div>

{% endblock %}

{% block page-js %}
    <script>
        // 给点赞和反对按钮绑定点击事件
        $(".digg").click(function () {
            // 1. 先判断有没有登录？
            if (!'{{ request.user.username }}') {
                // 如果没有登录就跳转到登录页面
                location.href = '/login/?next={{ request.get_full_path }}'
            }
            // 已经登录可以点赞或反对
            var userId = '{{ request.user.id }}';
            var articleId = '{{ article.id }}';
            // 如何区分是点赞还是反对？
            var isUp = $(this).hasClass('diggit');
            // 向后端发请求
            $.ajax({
                url: '/mengmeng/',
                type: 'post',
                data: {
                    csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val(),
                    userId: userId,
                    articleId: articleId,
                    isUp: isUp
                },
                success: function (res) {
                    console.log(res);
                    if (res.code !== 0) {
                        // 只需要把错误提示显示出来就可以
                        $("#digg_tips").text(res.msg);
                    } else {
                        // 1. 先把点赞数或反对数更新一下
                        if (isUp) {
                            // 更新点赞数
                            var $UpSpan = $("#digg_count");
                            $UpSpan.text(+$UpSpan.text() + 1);
                        } else {
                            var $downSpan = $("#bury_count");
                            $downSpan.text(+$downSpan.text() + 1)
                        }
                        // 2. 再显示提示
                        $("#digg_tips").text(res.msg);
                    }
                }
            })
        });

        // 给评论按钮绑定事件
        $("#submit-comment").click(function () {
            var userId = "{{ request.user.id }}";
            var content = $("#new-comment").val();
            var articleId = "{{ article.id }}";
            var parentId = $(this).data("pid") || "";
            if (parentId){
                content = content.slice(content.indexOf('\n')+1,);
            }
            $.ajax({
                url: "/comment/",
                type: "post",
                data: {
                    parent_id: parentId,
                    user_id: userId,
                    content: content,
                    article_id: articleId,
                    csrfmiddlewaretoken: $('[name="csrfmiddlewaretoken"]').val(),
                },
                success: function (res) {
                    console.log(res);
                    if (res.code === 0) {
                        var data = res.data;
                        var num = $(".comment-list>div").length + 1;
                        // 创建评论成功，通过js在评论列表里加一个新的评论
                        var commentHtml = `
                        <div href="#" class="list-group-item">
                            <h4 class="list-group-item-heading comment-header">
                                <span>${ num }楼</span>
                                <span>${ data.create_time }</span>
                                <span>${ data.username }</span>
                                <span class="pull-right replay">回复</span>
                            </h4>
                            <p class="list-group-item-text comment-content">
                                ${ data.content }
                            </p>
                        </div>
                        `;
                        // console.log(commentHtml);
                        $(".comment-list").append(commentHtml);
                        // 清空textarea
                        $("#new-comment").val('');
                        $("#submit-comment").removeData("pid");
                    }
                }
            })
        });
        // 给回复按钮绑定事件
        {#$(".replay").click(function () {#}
        $(".comment-list").on("click", ".replay", function () {
            // 1. 光标聚焦到评论框
            // 2. 添加一个@xxx的提示
            var replayName = $(this).prev().text();
            $("#new-comment").focus().val("@"+replayName+"\n");
            // 把当前评论的id值，偷偷存到提交按钮中
            var pID = $(this).parent().parent().attr("my-id");
             $("#submit-comment").data("pid", pID);
        })


    </script>
{% endblock %}

bbs/templates/backend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
</head>
<body>

<div class="container-fluid" style="margin-top: 70px">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-info">
              <div class="panel-heading">操作</div>
              <div class="panel-body">
                  <a href="/blog/add_article/">添加新文章</a>
              </div>
            </div>
        </div>
        <div class="col-md-10">
            <table class="table table-striped">
              <thead>
                <tr>
                    <th>标题</th>
                    <th>评论数</th>
                    <th>点赞数</th>
                    <th>操作</th>
                    <th>操作</th>
                </tr>
              </thead>
                <tbody>
                    {% for article in article_list %}
                        <tr>
                        <td><a href="/blog/{{ article.user.username }}/p/{{ article.id }}/">{{ article.title }}</a></td>
                        <td>{{ article.comment_count }}</td>
                        <td>{{ article.up_count }}</td>
                        <td><a href="">删除</a></td>
                        <td><a href="">编辑</a></td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

</body>
</html>

bbs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/blog.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
</head>
<body>
<!-- 博客的顶部菜单 开始-->
<div class="head"></div>
<!-- 博客的顶部菜单 结束-->


<!-- 页面主题 开始-->
<div class="container">
    <div class="row">
        <!-- 左侧侧边栏 开始 -->
        <div class="col-md-2">
            {% load s12 %}
            {% left_menu username %}

            <div>{% hehe 'alex' %}</div>
        </div>
        <!-- 左侧侧边栏 结束 -->
        <!-- 右侧文章列表 开始 -->
        <div class="col-md-10">
            {% block page-main %}

            {% endblock page-main %}
        </div>
        <!-- 右侧文章列表 结束 -->
    </div>
</div>
<!-- 页面主题 结束-->
<script src="/static/js/jquery.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
{% block page-js %}

{% endblock %}
</body>
</html>

bbs/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BBS首页</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bbs.css">
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/blog/backend/">{{ request.user.username }}</a>
                </li>
                <li>
                    <img src="/media/{{ request.user.avatar }}" alt=""
                         style="height: 50px;width: 50px;border-radius: 50%">
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!-- 页面主题内容 开始-->
<div class="container-fluid">
    <div class="row">
        <!-- 左侧广告区 开始-->
        <div class="col-md-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">左侧广告区</h3>
                </div>
                <div class="panel-body">
                    广告位招商
                </div>
            </div>
        </div>
        <!-- 左侧广告区 结束-->
        <!-- 文章展示区 开始-->
        <div class="col-md-8">

            <div class="article-list">
                {% for article in article_list %}
                    <!-- 文章 开始-->
                    <div class="article">
                        <div class="media">
                            <h3 class="media-heading">{{ article.title }}</h3>
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object author-avatar" src="/media/{{ article.user.avatar }}"
                                         alt="">
                                </a>
                            </div>
                            <div class="media-body">
                                <div class="article-desc">
                                    {{ article.desc }}
                                </div>
                                <div class="article-footer">
                                    <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a></span>
                                    <span>发布于&nbsp;{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
{#                                    <span class="glyphicon glyphicon-comment">评论({{ article.comment_set.all.count }})</span>#}
{#                                    <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.articleupdown_set.all.count }})</span>#}
                                    <span class="glyphicon glyphicon-comment">评论({{ article.comment_count }})</span>
                                    <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- 文章 结束-->
                {% endfor %}
            </div>
            <!-- 分页 开始-->
            {{ page_html|safe }}
            <!-- 分页 结束-->
        </div>
        <!-- 文章展示区 结束-->
        <!-- 右侧广告区 开始-->
        <div class="col-md-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">右侧广告区</h3>
                </div>
                <div class="panel-body">
                    性感荷官 在线发牌
                </div>
            </div>
        </div>
        <!-- 右侧广告区 结束-->
    </div>
</div>
<!-- 页面主题内容 开始-->

{{ d.items }}
<script src="/static/js/jquery.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.js"></script>
</body>
</html>

bbs/templates/left_menu.html
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">文章分类</h3>
    </div>
    <div class="panel-body">
        {% for category in category_list %}
            <p>
                <a href="/blog/{{ username }}/category/{{ category.title }}/">{{ category.title }}({{ category.article_set.all.count }})</a>
            </p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">文章标签</h3>
    </div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p>
                <a href="/blog/{{ username }}/tag/{{ tag.title }}/">{{ tag.title }}({{ tag.article_set.all.count }})</a>
            </p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title">日期归档</h3>
    </div>
    <div class="panel-body">
        {% for archive in archive_list %}
            <p><a href="/blog/{{ username }}/archive/{{ archive.y_m }}/">{{ archive.y_m }}({{ archive.c }})</a></p>
        {% endfor %}
    </div>
</div>

bbs/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/bbs.css">
</head>
<body>
{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="login-form">
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}">{{ form_obj.username.label }}</label>
                    {{ form_obj.username }}
                    <span class="help-block"></span>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}">{{ form_obj.password.label }}</label>
                    {{ form_obj.password }}
                    <span class="help-block"></span>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}">{{ form_obj.re_password.label }}</label>
                    {{ form_obj.re_password }}
                    <span class="help-block"></span>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.phone.id_for_label }}">{{ form_obj.phone.label }}</label>
                    {{ form_obj.phone }}
                    <span class="help-block"></span>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}">{{ form_obj.email.label }}</label>
                    {{ form_obj.email }}
                    <span class="help-block"></span>
                </div>
                <div class="form-group">
                    <label for="avatar">头像<img id="avatar-img" src="/static/default.png" alt="" style="height: 80px;width: 80px;margin-left: 15px"></label>

                    <input type="file" accept="image/*" id="avatar" style="display: none;">
                </div>
                <div class="form-group">
                    <label for="v-code" style="display: block;">验证码</label>
                    <input type="text" id="v-code" class="form-control" style="width: 250px;display: inline-block">
                    <img src="/v-code/" id="i1" style="float: right">
                    <span id="error-p" class="err-text"></span>
                </div>
                <button id="reg-btn" type="button" class="btn btn-default">注册</button>
            </form>
        </div>
    </div>
</div>

<script src="/static/js/jquery.js"></script>
<script>
    $("#reg-btn").click(function () {
        // 1. 取到用户填写的数据
        var fd = new FormData();
        fd.append("username", $("#id_username").val());
        fd.append("password", $("#id_password").val());
        fd.append("re_password", $("#id_re_password").val());
        fd.append("phone", $("#id_phone").val());
        fd.append("email", $("#id_email").val());
        fd.append("v_code", $("#v-code").val());
        fd.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        fd.append('avatar', $("#avatar")[0].files[0]);
        // 2. 往后端发post请求
        $.ajax({
            url: '/reg/',
            type: 'post',
            data: fd,
            processData: false,
            contentType: false,
            success:function (res) {
                console.log(res);
                if (res.code === 2){
                    // 验证码有错误
                    $("#error-p").text(res.msg);
                }else if (res.code === 0){
                    // 注册成功
                    location.href = res.msg;
                }else if (res.code === 1){
                    console.log(res.msg);
                    // 遍历取出所有的错误提示信息，在页面上展示出来
                    $.each(res.msg, function (k,v) {
                        $("#id_"+k).next().text(v[0]).parent().addClass('has-error');
                    })
                }
            }
        })
    });

    // 每一个input标签获取焦点的时候，把自己下面的span标签内容清空，把父标签的has-error样式移除
    $("input.form-control").focus(function () {
        $(this).val('').next("span").text('').parent().removeClass('has-error');
    });

    $("#v-code").focus(function () {
        $(this).val('').next().next().text('');
    });
    // 前端页面实现头像预览
    // 当用户选中文件之后，也就是头像的input标签有值时触发
    $("#avatar").change(function () {
        // 找到用户选中的那个文件
        var file = this.files[0];
        // 生成一个读文件的对象
        var fr = new FileReader();
        // 从文件中读取头像文件数据
        fr.readAsDataURL(file);
        // 等到读完之后
        fr.onload = function () {
            // 将头像img标签的src属性更换成我选中的那个文件
            $("#avatar-img").attr("src", fr.result)
        }
    })

</script>
</body>
</html>

bbs/templates/xx.html
<a>{{ str }}</a>